# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				bee = true
				axolotl = true
				zoglin = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				camel = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				ender_dragon = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				sniffer = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				villager = true
				wolf = true
				skeleton_horse = true
				tnt_minecart = true
				zombie_villager = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				snow_golem = true
				cod = true
				spider = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				end_slime = true
				end_fish = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				moobloom = true
				mauler = true
				iceologer = true
				rascal = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true
				verdant = true
				thicket = true

